# Generated by `rjournal_pdf_article()` using `knitr::purl()`: do not edit by hand
# Please edit main.Rmd to modify this file

## ----setup, include=FALSE-----------------------------------------------------
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(plotly)
library(ggplot2)
library(palmerpenguins)
library(kableExtra)
library(dplyr)

# Tables
library(table1)

# Plots
library(ggplot2)
library(ggplotify)

# Load Metabolomics Pipeline
library(MetabolomicsPipeline)

library(SummarizedExperiment)


## ----Workflow, out.width = "100%", out.height = "30%", fig.cap = "MetabolomicsPipeline workflow", echo=FALSE----
knitr::include_graphics("figures/Workflow.png")


## ----SEOrganization, out.width = "100%", out.height = "30%", fig.cap = "Figure 2. Organization of Metabolon Inc data into a SummarizedExperiment", echo=FALSE----
knitr::include_graphics("figures/SEOrganization.png")


## ----loadData-----------------------------------------------------------------
# Load Metabolon data from the Excel file
# dat <- loadMetabolon(path = "../data/Metabolon.xlsx")
data("demoDat", package = "MetabolomicsPipeline")

dat <- demoDat


################################################################################
### Create Table 1 #############################################################
################################################################################
# Create table 1
tbl1 <- table1(~ GROUP_NAME + TIME1 | Gender,
    data = colData(dat)
)

# Display table 1
tbl1




## ----PCA_Plots----------------------------------------------------------------
# Colored by Gender
metabolite_pca(dat, Assay = "normalized", meta_var = "Gender")



## ----heatmaps-----------------------------------------------------------------
# Heatmap with 2 group and stratified
metabolite_heatmap(dat,
    top_mets = 50,
    group_vars = c("GROUP_NAME", "TIME1"),
    strat_var = "Gender",
    caption = "Heatmap Arranged By Group and TIME",
    Assay = "normalized",
    sample_names = "PARENT_SAMPLE_NAME",
    TIME1,GROUP_NAME # Variables to use for annotation column names
)




## ----subpathway_analysis------------------------------------------------------
################################################################################
## Stratified Analysis #########################################################
################################################################################

# Stratified Analysis
stratified <- subpathway_analysis(dat,
    treat_var = "GROUP_NAME",
    block_var = "TIME1",
    strat_var = "Gender",
    Assay = "normalized",
    subPathwayName = "SUB_PATHWAY",
    chemName = "CHEMICAL_NAME",
    superPathwayName = "SUPER_PATHWAY"
)


################################################################################
### Results Plots ##############################################################
################################################################################

# 1. significant subpathways by model type
subpath_by_model(stratified)

# 2. Percentage of signficant subpathways within superpathways
subpath_within_superpath(stratified)

# 3. Metabolites within subpathway
tables <- met_within_sub(stratified,
    subpathway = "Drug - Topical Agents"
)

### Females
tables[[1]]

### Males
tables[[2]]



## ----lineplotsAndBoxplots-----------------------------------------------------
################################################################################
### BoxPlots ###################################################################
################################################################################

subpathway_boxplots(dat,
    subpathway = "Drug - Topical Agents", block_var = TIME1,
    treat_var = GROUP_NAME, Assay = "normalized",
    CHEMICAL_NAME = "CHEMICAL_NAME",
    SUB_PATHWAY = "SUB_PATHWAY",
    Gender == "Male" # only using female samples
) +
  xlab("Time")


################################################################################
## Line plots ##################################################################
################################################################################

# Set up data
dat$TIME1 <- as.numeric(factor(dat$TIME1,
    levels = c("PreSymp", "Onset", "End")
))

# Create line plots
subpathway_lineplots(dat,
    subpathway = "Drug - Topical Agents",
    block_var = TIME1, treat_var = GROUP_NAME,
    Assay = "normalized",
    CHEMICAL_NAME = "CHEMICAL_NAME",
    SUB_PATHWAY = "SUB_PATHWAY",
    Gender == "Male"
) +
    xlab("Time")


## ----PairwiseAnalysis---------------------------------------------------------
################################################################################
#### Run Pairwise Comparisons ##################################################
################################################################################

strat_pairwise <- metabolite_pairwise(dat,
    form = "GROUP_NAME*TIME1",
    Assay = "normalized",
    strat_var = "Gender",
    mets = NULL
)


## ----interactive-visualization,eval = knitr::is_html_output(), layout = "l-page-outset"----
#> ###############################################################################
#> ## Create Estimate Heatmap #####################################################
#> ################################################################################
#> 
#> met_est_heatmap(strat_pairwise$Female, dat,
#>     interactive = TRUE,
#>      SUB_PATHWAY = "SUB_PATHWAY",
#>     CHEMICAL_NAME = "CHEMICAL_NAME",
#>     plotlyTitle = "Estimate Heatmap (Female)",
#>     main = "Log fold change heatmap"
#> )
#> 
#> ################################################################################
#> ## Create P-value Heatmap ######################################################
#> ################################################################################
#> # Female
#> met_p_heatmap(strat_pairwise$Female, dat,
#>     interactive = TRUE, show_rownames = FALSE,
#>     plotlyTitle = "Pvalue Heatmap (Male)",
#>     main = "Pvalue Heatmap"
#> )
#> 


## ----static-visualization,eval = knitr::is_latex_output()---------------------
###############################################################################
## Create Estimate Heatmap #####################################################
################################################################################

met_est_heatmap(strat_pairwise$Female, dat,
    interactive = FALSE,
     SUB_PATHWAY = "SUB_PATHWAY",
    CHEMICAL_NAME = "CHEMICAL_NAME",
    plotlyTitle = "Estimate Heatmap",
    main = "Log fold change heatmap",
    show_rownames = FALSE
)

################################################################################
## Create P-value Heatmap ######################################################
################################################################################
# Female
met_p_heatmap(strat_pairwise$Female, dat,
    interactive = FALSE, show_rownames = FALSE,
    plotlyTitle = "Pvalue Heatmap",
    main = "Pvalue Heatmap"
)



